language: scala
scala: 2.12.6
jdk: oraclejdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
    - '.hoarder-cache'

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "gY7IzGZHiix2yoKsac22cwk8KuYI3gRWK+ZOlqQpQgsBSIBB6Ri8KgxZlY/OuZzy8IfOjUWoHhBHr3zV3dhvyfpW/KvGOq3XSAhzQ016EgxC0THO7RvMgVErTIXITNf1pE7JzvMh4wR+emqnIlH+1SKxV2JJsXANjupwM6DAxeakNw3t8piE2ZzQAdTanWoyuk6VoK+OFkHgMLsVcaBBQlYOvKBA1ZWpYID2zRlMkO2teTYT+nYaew3GEz8Bn2U7aOlICEQPfcT7orXw0pGgKVkg9DwO6pn0Wr1VuShYaweIWA6X2ftY1EUBDn9dMLbFgj3jcjE9VnYLvERloE84KvavNpDkXmFi9QoHhxEukSoySNznVI7jffKNcCIpw2DaBbnltmu52aazDAP871nn5d7dkLQnvN8wo5c9FJDq05z89FDTnqRIP9CT/Ns8RPkUhPWVn9l15ylGHJ5CWjcpka2Pczrget+KuOPtCYMPyryK3u94DjlMqhrmbg1kiZEHM92YfKPK73laiY6chqDAhP3JwdLWIbOxdvgVDXBhmqBwUSMGpLgsomcd25SOrn8Gx7C7qQD48+yp+322ovgko7qJA9Sh2/ah32gyyIA2246YFZMcKMh2tNfT4eoRaVl9J0hqIuSWyWigr0VYTBIsusnpVc9zY9Kysy/1OvCcvts="
    # GITHUB_TOKEN
    - secure: "R9+gKku29p1KXjm12E/RuheEFvuJzBry8AOjhGZ9MQTauoKf/8U/zFLB5PJebhb86WzYJg6aEILYKraA914p/xp9wREuDEbCmS/P8h5MgKxnBQz5+ZEUAFR9EVgGP6EfW91x/1bVA9+1/r8NcvPv8R7Oex2uNd7JZwyCK6e55EPn46zutFjv8sdh/Ou4BzGaseZWOF4Y29PSn2cm4c3p362SavLhGTogkGhriDN7b0Cp59qI7xuVyvQwPYJ404EWkVrXHfBePxjb6Ab21qfxlIIFIry0PqFPmxObjFWB8DQ6YwCGhdUzZ9Kr/kHDm90clOyFRiuKhSTlJmd6sZ+za8Djs+NdGyodOnJ5T9djDbTXt7LrU/NrMfHOdSeIsWAuRuIKZMuDhSAFjcGPVmvu/NO4UQjvlhtUcDS6lpqKz4dzREpi/BMTICwA/1vMCUoUg4UyAEfDxUTwk8kttwnJ+kILXC3RROgg5oFrnxC8IjaSbJXckB+5bxsCGBIn0c/xdUDinlmpRYzNeStuhqwIGlfdBZPqID30EsP+Z4SJlwZitshoweuT643PgZ1f4d9cKxAd0KSmT6mHEzPqlxOBD35DbgLdBOs3B19oSxPr1ymaAG26g58RpZ6rkl98KgiD7yjqNC9+l/ct+ru5EcwvBYA0iamrJ4RacJm5NY+Dhos="
    # GITHUB_ACCESS_TOKEN
    - secure: "R9+gKku29p1KXjm12E/RuheEFvuJzBry8AOjhGZ9MQTauoKf/8U/zFLB5PJebhb86WzYJg6aEILYKraA914p/xp9wREuDEbCmS/P8h5MgKxnBQz5+ZEUAFR9EVgGP6EfW91x/1bVA9+1/r8NcvPv8R7Oex2uNd7JZwyCK6e55EPn46zutFjv8sdh/Ou4BzGaseZWOF4Y29PSn2cm4c3p362SavLhGTogkGhriDN7b0Cp59qI7xuVyvQwPYJ404EWkVrXHfBePxjb6Ab21qfxlIIFIry0PqFPmxObjFWB8DQ6YwCGhdUzZ9Kr/kHDm90clOyFRiuKhSTlJmd6sZ+za8Djs+NdGyodOnJ5T9djDbTXt7LrU/NrMfHOdSeIsWAuRuIKZMuDhSAFjcGPVmvu/NO4UQjvlhtUcDS6lpqKz4dzREpi/BMTICwA/1vMCUoUg4UyAEfDxUTwk8kttwnJ+kILXC3RROgg5oFrnxC8IjaSbJXckB+5bxsCGBIn0c/xdUDinlmpRYzNeStuhqwIGlfdBZPqID30EsP+Z4SJlwZitshoweuT643PgZ1f4d9cKxAd0KSmT6mHEzPqlxOBD35DbgLdBOs3B19oSxPr1ymaAG26g58RpZ6rkl98KgiD7yjqNC9+l/ct+ru5EcwvBYA0iamrJ4RacJm5NY+Dhos="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "J7rPt6xTkOhDF1K+1Bw0corEtBpuk72CBKnyRGZWO6OUFwbuZOWaTxTGCp/0qZ0UDqn952I3b65Hi5RmEl0XAScGM9ajhPu1v2YFHeIMkCATZ/OBoqR9Vxg6MRvtg23a8YYbiB44yupgCmVxNf8scHMMjTyqtp2U929V9f6sy4Eod63OKBZSBtbIYDOJocoMwbTQ2diaM4YSKFPSFmWd3s6NG02fhyYD0PXDGbSbCVAx8nKpQVX7yabzE20E8jL4Zs6U2x9zvg2tQt1FkD1wVIiErUxiS5dcwR3l3+IbUmLUhSr/zZAMZFcTJUVGe/LH2oseC8fCf1y+jtlGDyH7JalyTKQdid4Ouw7wNgA/k3H2XZl6QUYnMlxeYha+w/VO/pjehxL2e/2clNW2g8PkryC+slV93Dni/8UVk+b6/LgavErreXpR+24l9Io3QCHVlMDNO9OgY+bhEAVLRyOnphbOCtdt+qB72DzautyZ4WoacjspMDHw0JHtGLkpTGjy2Mik4DLY5c0O025esURiHHyn41pRJD9Nln371dOrCMwZ1tR8/YAX4JiukSWCeRdhMHJOozU2mszssyU9yVat5kflaMEHXs2UA1tkdOlKMN+A7Im4sYpTGpVXjU71zQ+H+j0kzh8UpOEgpPtq7roFK1YIX2S8OE4vm+koIVeQcLk="

jobs:
  include:
    - stage: test
      script:
        - set -e
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/sbt-quasar-datasource'

      git:
        depth: false

after_success:
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
